version: '3'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes: 
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_config:/config
      - ./caddy_data:/data
    links:
      - sanity

  sanity:
    image: eqlabs/crypto-sanity-preserver:latest
    container_name: sanity
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: sanity
    restart: unless-stopped
    env_file:
      - .env
    #ports:
      #- '1337:1337'
    links:
      - mongo
    volumes:
      - data:/home/python/app/data
      - thumbs:/home/python/static/thumbs

  mongo:
    image: mongo:latest
    container_name: mongo-sanity
    hostname: mongo
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    
  watchtower:
    command: --label-enable --cleanup --interval 300
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: none
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
    data:
      external: true
    thumbs:
      external: true
    mongo:
      external: true
